export default [
  {
    id: '1',
    name: 'Esther Howard',
    avatar: 'https://i.pravatar.cc/300',
    isFollowing: false,
    me: false,
    followersCount: 62,
  },
  {
    id: '2',
    name: 'Leslie Alexandar',
    avatar: 'https://i.pravatar.cc/300',
    isFollowing: true,
    me: false,
    followersCount: 102,
  },
  {
    id: '3',
    name: 'Robert Fox',
    avatar: 'https://i.pravatar.cc/300',
    isFollowing: false,
    me: false,
    followersCount: 58,
  },
  {
    id: '4',
    name: 'Kristin Watson',
    avatar: 'https://i.pravatar.cc/300',
    isFollowing: false,
    me: false,
    followersCount: 32,
  },
  {
    id: '5',
    name: 'Cody Fisher',
    avatar: 'https://i.pravatar.cc/300',
    isFollowing: true,
    me: false,
    followersCount: 12,
  },
  {
    id: '6',
    name: 'Jane Cooper',
    avatar: 'https://i.pravatar.cc/300',
    isFollowing: false,
    me: false,
    followersCount: 48,
  },
  {
    id: '7',
    name: 'Usman Suleiman',
    avatar: 'https://i.pravatar.cc/300',
    isFollowing: false,
    me: true,
    followersCount: 48,
  },
];
